blank_issues_enabled: false
contact_links:

  - name: ğŸ¤·â€â™€ï¸ Questions or need help?
    url: https://github.com/victornpb/undiscord/discussions/categories/1-questions-answers
    about: Check existing questions or post a new one
    
  - name: ğŸ’¬ Discussions
    url: https://github.com/victornpb/undiscord/discussions/categories/2-discussions
    about: Start an open ended discussion
    
  - name: ğŸ’¡ Suggestions / Ideas
    url: https://github.com/victornpb/undiscord/discussions/categories/3-ideas
    about: Check existing suggestions or share ideas for new features
    
